openapi: 3.0.1
info:
  title: HelloAPI
  description: API Definition of HelloAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/hello
- url: https://localhost:8253/hello
paths:
  /:
    get:
      parameters:
        - name: message
          in: query
          schema:
            type: string
      responses:
        default:
          description: Default response
